# Generated by Django 4.2 on 2023-05-30 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songnotesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songnote',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='songnotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
